### ISSUE TITLE
Convert directory of templates to charts

### ISSUE THREAD

**Issue by Gl4di4torRr** [redhat-cop/template2helm#17]
As an OpenShift user, I want the ability to convert a directory of templates to helm charts.

**Comment by cpitman** [comment]
Is each template a separate helm chart? If so, does this make sense in lieu of scripting?

```for f in *; do template2helm convert --template $f --chart /tmp/charts/$f; done```

**Comment by etsauer** [comment]
Interesting point @cpitman. I am generally open to features that make this easier, especially since its such a simple tool to begin with. however, I would like to come up with some examples of how building this into the tool is better and has more value than embedding it in a for loop.

Also, I think that if we took this feature on, I would want to wait until @InfoSec812 gets done with the refactor he's working on to prepare for #13

**Comment by Gl4di4torRr** [comment]
@cpitman There are a number of commands that you could say a script would work. However, I think the point is that it's easier for the consumer to use. I have a directory called `templates` where each template will need to be turned into a chart. Yes, I can write a script. However, if there was a `-d` flag or something to that nature, it would make my life and others better.

**Comment by garethahealy** [comment]
archiving
